<a href="https://colab.research.google.com/github/AanchalA/PyTorch-Deep-Learning-Bootcamp/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [PyTorch Fundamentals Course Resource](https://www.learnpytorch.io/00_pytorch_fundamentals/)

- [Precision in Computing](https://en.wikipedia.org/wiki/Precision_(computer_science)
- https://matrixmultiplication.xyz/
- https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

In [ ]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
torch.cuda.is_available()

False

# Creating Tensors

In [ ]:
torch.empty(3, 2)

tensor([[6.8575e+22, 4.6114e+24],
        [3.1842e-15, 3.0820e+32],
        [1.7667e+22, 1.8177e+31]])

In [ ]:
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
# Scalar
scalar = torch.tensor(3)     ## Creating a tensor from a list

print(scalar)
print(scalar.dtype)
print(scalar.shape)
print(scalar.size())
print(scalar.device)
print(scalar.ndim)
print(scalar.item())

tensor(3)
torch.int64
torch.Size([])
torch.Size([])
cpu
0
3


In [ ]:
# Vector
vector = torch.tensor([2, 3, 5, 6])        ## Creating a tensor from a list
print(vector)
print(vector.dtype)
print(vector.shape)                     ## Gives the number of elements in the vector
print(vector.size())
print(vector.device)
print(vector.ndim)

tensor([2, 3, 5, 6])
torch.int64
torch.Size([4])
torch.Size([4])
cpu
1


In [ ]:
# Matrix
matrix = torch.tensor([[2, 3],
                        [3, 4]])        ## Creating a tensor from a list
print(matrix)
print(matrix.dtype)
print(matrix.shape)                     ## Gives the number of elements in the matrix or sub vectors
print(matrix.size())
print(matrix.device)
print(matrix.ndim)

tensor([[2, 3],
        [3, 4]])
torch.int64
torch.Size([2, 2])
torch.Size([2, 2])
cpu
2


In [ ]:
# Tensor
tensor = torch.tensor([[2, 3, 5, 6],
                        [3, 4, 7, 6],
                       [7, 8, 9, 0]])        ## Creating a tensor from a list
print(tensor)
print(tensor.dtype)
print(tensor.shape)                     ## Gives the number of elements in the tensor or sub vectors
print(tensor.size())
print(tensor.device)
print(tensor.ndim)

tensor([[2, 3, 5, 6],
        [3, 4, 7, 6],
        [7, 8, 9, 0]])
torch.int64
torch.Size([3, 4])
torch.Size([3, 4])
cpu
2


In [ ]:
# Tensor
tensor = torch.tensor([[[2, 3, 5, 6],
                        [3, 4, 7, 6],
                       [7, 8, 9, 0]]])        ## Creating a tensor from a list
print(tensor)
print(tensor.dtype)
print(tensor.shape)                     ## Gives the number of elements in the tensor or sub vectors
print(tensor.size())
print(tensor.device)
print(tensor.ndim)

tensor([[[2, 3, 5, 6],
         [3, 4, 7, 6],
         [7, 8, 9, 0]]])
torch.int64
torch.Size([1, 3, 4])
torch.Size([1, 3, 4])
cpu
3


In [ ]:
# Tensor
tensor = torch.tensor([[[[[2, 3, 5, 6],
                        [3, 4, 7, 6],
                       [7, 8, 9, 0]]]]])        ## Creating a tensor from a list
print(tensor)
print(tensor.dtype)
print(tensor.shape)                     ## Gives the number of elements in the tensor or sub vectors
print(tensor.size())
print(tensor.device)
print(tensor.ndim)

tensor([[[[[2, 3, 5, 6],
           [3, 4, 7, 6],
           [7, 8, 9, 0]]]]])
torch.int64
torch.Size([1, 1, 1, 3, 4])
torch.Size([1, 1, 1, 3, 4])
cpu
5


In [ ]:
# Tensor
tensor = torch.tensor([[[
                        [[2, 3, 5, 6],
                        [3, 4, 7, 6],
                        [7, 8, 9, 0]],
                        [[12, 23, 45, 5],
                        [2, 3, 4, 5],
                        [5, 6, 7, 8]]
                        ]]])        ## Creating a tensor from a list
print(tensor)
print(tensor.dtype)
print(tensor.shape)                     ## Gives the number of elements in the tensor or sub vectors
print(tensor.size())
print(tensor.device)
print(tensor.ndim)

tensor([[[[[ 2,  3,  5,  6],
           [ 3,  4,  7,  6],
           [ 7,  8,  9,  0]],

          [[12, 23, 45,  5],
           [ 2,  3,  4,  5],
           [ 5,  6,  7,  8]]]]])
torch.int64
torch.Size([1, 1, 2, 3, 4])
torch.Size([1, 1, 2, 3, 4])
cpu
5


In [ ]:
print(tensor[0])
print(tensor[0][0])
print(tensor[0][0][0])
print(tensor[0][0][0][0])
print(tensor[0][0][0][0][0])
print(tensor[0][0][0][0][0].item())

tensor([[[[ 2,  3,  5,  6],
          [ 3,  4,  7,  6],
          [ 7,  8,  9,  0]],

         [[12, 23, 45,  5],
          [ 2,  3,  4,  5],
          [ 5,  6,  7,  8]]]])
tensor([[[ 2,  3,  5,  6],
         [ 3,  4,  7,  6],
         [ 7,  8,  9,  0]],

        [[12, 23, 45,  5],
         [ 2,  3,  4,  5],
         [ 5,  6,  7,  8]]])
tensor([[2, 3, 5, 6],
        [3, 4, 7, 6],
        [7, 8, 9, 0]])
tensor([2, 3, 5, 6])
tensor(2)
2


## Creating Random Tensors

In [ ]:
torch.rand(3, 2)

tensor([[0.8869, 0.9758],
        [0.8340, 0.5714],
        [0.3350, 0.3020]])

In [ ]:
torch.randn(3, 2)           ## Normal Distrobution

tensor([[-0.5089, -1.9524],
        [ 1.2930, -0.5533],
        [-1.7458,  0.6482]])

In [ ]:
# Tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))           ## size = (height, width, n_colour_channels(R, G, B))
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


In [ ]:
ones = torch.ones(4, 5)
random = torch.rand(4, 5)
print(ones)
print(random)
print(ones * random)            ## Here elementwise multiplication operation happens

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.6039, 0.1227, 0.7464, 0.4889, 0.9022],
        [0.9593, 0.3882, 0.0263, 0.6441, 0.2032],
        [0.5394, 0.3415, 0.5553, 0.1126, 0.6286],
        [0.9057, 0.6511, 0.8022, 0.4142, 0.7474]])
tensor([[0.6039, 0.1227, 0.7464, 0.4889, 0.9022],
        [0.9593, 0.3882, 0.0263, 0.6441, 0.2032],
        [0.5394, 0.3415, 0.5553, 0.1126, 0.6286],
        [0.9057, 0.6511, 0.8022, 0.4142, 0.7474]])


In [ ]:
t = torch.arange(0, 10, 4)

In [ ]:
torch.zeros_like(t)

tensor([0, 0, 0])

In [ ]:
torch.ones_like(t)

tensor([1, 1, 1])

In [ ]:
torch.empty_like(t)

tensor([139553703218544, 139553703218544,              32])

In [ ]:
t.new_zeros(2, 3)            ## the returned Tensor has the same torch.dtype and torch.device as this tensor t.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
float_32_t = torch.randint(high=5, size=(1,2))
float_32_t

tensor([[4, 4]])

In [ ]:
float_32_t = torch.arange(0, 10, step=2, dtype=torch.float32)
print(float_32_t.dtype)
float_32_t

torch.float32


tensor([0., 2., 4., 6., 8.])

In [ ]:
t_16 = float_32_t.type(torch.float16)
t_16

tensor([0., 2., 4., 6., 8.], dtype=torch.float16)

In [ ]:
float_32_t * t_16

tensor([ 0.,  4., 16., 36., 64.])

In [ ]:
float_32_t * float_32_t.type(torch.complex128)

tensor([ 0.+0.j,  4.+0.j, 16.+0.j, 36.+0.j, 64.+0.j], dtype=torch.complex128)

## Getting Information from Tensors

In [ ]:
ten = torch.rand(3, 4)
print(ten.dtype)
print(ten.shape)
print(ten.size())
print(ten.device)
print(ten.ndim)

torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu
2


## Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 546 µs, sys: 102 µs, total: 648 µs
Wall time: 12.7 ms


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 7.26 ms, sys: 1.06 ms, total: 8.32 ms
Wall time: 18.8 ms


tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 691 µs, sys: 812 µs, total: 1.5 ms
Wall time: 5.89 ms


In [ ]:
ten_a = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
ten_b = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
ten_c = torch.tensor([[7, 8],
                      [9, 10],
                      [11, 12]])
print(ten_a.shape)
print(ten_b.shape)
print(ten_c.shape)

torch.Size([3, 2])
torch.Size([2, 3])
torch.Size([3, 2])


In [ ]:
torch.mm(ten_a, ten_c.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Tensor Aggregration
- Min, Max, Sum, Mean

In [ ]:
tensor = torch.arange(0, 100, step=10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(tensor), torch.max(tensor)

(tensor(0), tensor(90))

In [ ]:
tensor.min(), tensor.max()

(tensor(0), tensor(90))

In [ ]:
torch.sum(tensor)

tensor(450)

In [ ]:
tensor.sum()

tensor(450)

In [ ]:
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [ ]:
tensor.type(torch.float32).mean()

tensor(45.)

In [ ]:
torch.argmin(tensor), tensor.argmin()       ## Returns the index of the min element

(tensor(0), tensor(0))

In [ ]:
tensor[tensor.argmin().item()]

tensor(0)

In [ ]:
torch.argmax(tensor), tensor.argmax()       ## Returns the index of the max element

(tensor(9), tensor(9))

In [ ]:
tensor[tensor.argmax().item()]

tensor(90)

## Reshaping, Stacking, Squeezing and Unsqueezing
- Reshape - Reshapes the input tensor
- View - Returns the tensor in the specified shape, but maps to the same memory location.
- Stacking - Combining multiple tensors together, either on top of each other (vstack/vertical-stack/dim=0), side by side (h-stack, horizontal-stack/dim=1)
- Squeeze - Removes all '1' dimensions from the tensor
- Unsqueeze - Adds a '1' dimension to a target tensor.
- Permute - Return a view of the tensor with the dimensions permuted / swapped / rearranged in a certain way.

In [ ]:
import torch

In [ ]:
x = torch.arange(1., 10.)
print(x)
print(x.ndim)
print(x.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
1
torch.Size([9])


In [ ]:
# Reshape
# Adding an extra dimension to x, the new size should be factors of the original size.
reshaped = x.reshape(1, 9)
print(reshaped)
print(reshaped.ndim)
print(reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
2
torch.Size([1, 9])


In [ ]:
# View
# Returns the tensor in the specified shape, but maps to the same memory location.
# Any changes made to z will reflect in x
z = x.view(3, 3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z[:, 2] = 5
z, x

(tensor([[1., 2., 5.],
         [4., 5., 5.],
         [7., 8., 5.]]),
 tensor([1., 2., 5., 4., 5., 5., 7., 8., 5.]))

In [ ]:
## Stack - dim=0=vstack, dim=1=hstack (dim = 1 has a different behaviour than troch.hstack)
x_stacked = torch.stack([x, x, x, x], dim=1)        ## For dim=1, all the values of a column are getting concatenated into a single row
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [5., 5., 5., 5.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [5., 5., 5., 5.]])

In [ ]:
v_stacked = torch.vstack([x, x, x, x])      ## Same as torch.stack(dim=0)
v_stacked

tensor([[1., 2., 5., 4., 5., 5., 7., 8., 5.],
        [1., 2., 5., 4., 5., 5., 7., 8., 5.],
        [1., 2., 5., 4., 5., 5., 7., 8., 5.],
        [1., 2., 5., 4., 5., 5., 7., 8., 5.]])

In [ ]:
h_stacked = torch.hstack([x, x, x, x])      ## Here all the elements got stacked into a single row, one column after another.
h_stacked

tensor([1., 2., 5., 4., 5., 5., 7., 8., 5., 1., 2., 5., 4., 5., 5., 7., 8., 5.,
        1., 2., 5., 4., 5., 5., 7., 8., 5., 1., 2., 5., 4., 5., 5., 7., 8., 5.])

In [ ]:
## Squeeze
y = x.reshape(1, 3, 3, 1)
print(y)
s = y.squeeze()
print(s)
s[:, 0] = 5             ## Squeeze shares the memory location with the original tensor
s, y

tensor([[[[1.],
          [2.],
          [5.]],

         [[4.],
          [5.],
          [5.]],

         [[7.],
          [8.],
          [5.]]]])
tensor([[1., 2., 5.],
        [4., 5., 5.],
        [7., 8., 5.]])


(tensor([[5., 2., 5.],
         [5., 5., 5.],
         [5., 8., 5.]]),
 tensor([[[[5.],
           [2.],
           [5.]],
 
          [[5.],
           [5.],
           [5.]],
 
          [[5.],
           [8.],
           [5.]]]]))

In [ ]:
print(x.shape)
print(x.ndim)
x.unsqueeze(dim=0).shape, x.unsqueeze(dim=1).shape

torch.Size([9])
1


(torch.Size([1, 9]), torch.Size([9, 1]))

In [ ]:
## Permute
y.shape, y.permute(1, 0, 3, 2).shape

(torch.Size([1, 3, 3, 1]), torch.Size([3, 1, 1, 3]))

In [ ]:
y, y.permute(1, 0, 3, 2)

(tensor([[[[5.],
           [2.],
           [5.]],
 
          [[5.],
           [5.],
           [5.]],
 
          [[5.],
           [8.],
           [5.]]]]),
 tensor([[[[5., 2., 5.]]],
 
 
         [[[5., 5., 5.]]],
 
 
         [[[5., 8., 5.]]]]))

## Indexing

In [ ]:
import torch

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x.ndim)
print(x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0].item()

1

In [ ]:
# ":" can be used to select all of the elements of that particular dimension
x[:, 0]             ### Taking all the dimensions from dim=0 and 0th element from dim=1

tensor([[1, 2, 3]])

In [ ]:
# taking all values from dim 0 and 1 and 1st element from dim=2
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# taking all values from dim=0 but only 1st index from dim 1 and 2
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x = torch.arange(100).reshape(2, 2, 5, 5)
x

tensor([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24]],

         [[25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49]]],


        [[[50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59],
          [60, 61, 62, 63, 64],
          [65, 66, 67, 68, 69],
          [70, 71, 72, 73, 74]],

         [[75, 76, 77, 78, 79],
          [80, 81, 82, 83, 84],
          [85, 86, 87, 88, 89],
          [90, 91, 92, 93, 94],
          [95, 96, 97, 98, 99]]]])

In [ ]:
x[:, 0, 4, :]

tensor([[20, 21, 22, 23, 24],
        [70, 71, 72, 73, 74]])

## PyTorch and NumPy

In [ ]:
## NumPy Array to Tensor
import numpy as np
import torch

In [ ]:
array = np.arange(1.0, 8.0)                     ## default dtype == float64
tensor = torch.from_numpy(array)                ## default dtype == float32
array, tensor, tensor.type(torch.float32), tensor.type(torch.float32).dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
# array += 1
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
## Tensor to Numpy Array
ones = torch.ones(7)
n_array = ones.numpy()
ones, n_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
n_array.dtype

dtype('float32')

In [ ]:
ones = ones + 1
ones, n_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
- Trying to take out the random out of random
- https://pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed

In [ ]:
rand_A = torch.rand(3, 4)
rand_B = torch.rand(3, 4)
print(rand_A)
print(rand_B)
print(rand_A == rand_B)

tensor([[0.7890, 0.0113, 0.6176, 0.7638],
        [0.2827, 0.4934, 0.6360, 0.2694],
        [0.5124, 0.3348, 0.9193, 0.1261]])
tensor([[0.7754, 0.4756, 0.9363, 0.9576],
        [0.6828, 0.1344, 0.2629, 0.7087],
        [0.9067, 0.0379, 0.9578, 0.1972]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [ ]:
torch.manual_seed(RANDOM_SEED)
rand_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_D = torch.rand(3, 4)

print(rand_C)
print(rand_D)
print(rand_C == rand_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## LEN() V/s NUMEL()

In [ ]:
rand_D

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
len(rand_D)

3

In [ ]:
rand_D.numel()

12

# On CPU V/s On GPU

In [ ]:
import torch

In [ ]:
# device will be 'cuda' if a GPU is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# creating a CPU tensor
cpu_tensor = torch.rand(10)#.to(device)
# moving same tensor to GPU
gpu_tensor = cpu_tensor.to(device)

print(cpu_tensor, cpu_tensor.dtype, type(cpu_tensor), cpu_tensor.type())
print("\n")
print(gpu_tensor, gpu_tensor.dtype, type(gpu_tensor), gpu_tensor.type())
print("\n")
print(cpu_tensor*gpu_tensor)

tensor([0.7622, 0.6634, 0.7805, 0.7244, 0.2123, 0.7325, 0.3430, 0.6874, 0.1623,
        0.3456]) torch.float32 <class 'torch.Tensor'> torch.FloatTensor


tensor([0.7622, 0.6634, 0.7805, 0.7244, 0.2123, 0.7325, 0.3430, 0.6874, 0.1623,
        0.3456]) torch.float32 <class 'torch.Tensor'> torch.FloatTensor


tensor([0.5809, 0.4401, 0.6092, 0.5248, 0.0451, 0.5366, 0.1176, 0.4725, 0.0263,
        0.1194])


In [ ]:
cpu_tensor.dtype, type(cpu_tensor), cpu_tensor.type()

(torch.float32, torch.Tensor, 'torch.FloatTensor')

In [ ]:
gpu_tensor.cpu().detach().numpy()               ## Creating numpy array from a gpu tensor
# Here cpu() will move the data to cpu
# detach() - will remove all the gradient values and keep only the weight values. Detaching the tensor from the computational graph.
# numpy() - will covnvert the data to a numpy array.

array([0.66258526, 0.34856766, 0.22606683, 0.7315991 , 0.43217194,
       0.4060076 , 0.518014  , 0.21797276, 0.80032915, 0.7552764 ],
      dtype=float32)